config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "submission#index"
  get '/sift', to: 'sift#index'
  get '/submissions/new', to: 'submission#new'
  post '/submissions/new', to: 'submission#create'
  get '/about-us', to: 'submission#about-us'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/submission.rb
class Submission < ApplicationRecord

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :days_running

  def days_running
    @days_running = Date.today.mjd - Date.new(2022,4,5).mjd
  end
end

app/controllers/sift_controller.rb
class SiftController < ApplicationController
  SIFTS = 2

  def index
    @all_sifts = Submission.where(used: false).where(today: false).to_a

    @sifts = []
    @sifts.append(@all_sifts[0])
    @sifts.append(@all_sifts[1])
  end

end

app/controllers/submission_controller.rb
class SubmissionController < ApplicationController

  POSTS = 6

  def index
    @submissions = Submission.all
    @todays_posts = []

    # find today's posts (if they exist)
    for submission in @submissions do
      if submission.used_date = Date.today
        @todays_posts.append()
      end
    end

    if @todays_posts.length < POSTS
      @todays_posts = build_todays_posts()
    end

    @css_random = build_random_css()

    return @todays_posts, @css_random
  end

  def new
    @submission = Submission.new
  end

  def create
    @submission = Submission.new(submission_params)

    if hasFields(@submission) && hasUniqueUrl(@submission)
      @submission.save
      redirect_to root_path, notice: "Thank you for submitting a new notice."
    else
      redirect_to submissions_new_path, alert: "There was an error submitting your notice."
    end
  end

private
  def hasFields(object)
    object.headline != nil
    object.url != nil
  end

  def hasUniqueUrl(object)
    @submissions = Submission.all

    @submissions.each do |submission|
      if object.url == submission.url
        p "URL is not unique"
        return false
      end
    end

    return true
  end

  def submission_params
    params.require(:submission).permit(:headline, :url)
  end

  def build_random_css
    output = []
    output.append(rand(0..7))

    7.times do
      random_num = rand(0..7)

      if output[-1] == random_num && random_num < 7
        output.append(random_num+1)
      elsif output[-1] == random_num && random_num == 7
        output.append(random_num-1)
      else
        output.append(random_num)
      end
    end

    return output
  end

  def mark_todays(posts)
    for post in posts do
      post.today = true
      post.used_date = Date.today
      post.save
    end
  end

  def build_todays_posts()
    unused_posts = []

    # find posts that have not been used
    for submission in @submissions do
      if !submission.used
        unused_posts.append(submission)
      end
    end

    # get the top 25% of the unused posts by score
    unused_posts.sort_by { |post| post.score }
    quarter = (unused_posts.length() / 4)
    posts_to_check = unused_posts[0..quarter]

    # Get images #TODO: refactor to cron job
    for post in posts_to_check
      if post.image_url == nil
        get_image(post)
      end
    end

    unused_posts.each_with_index do |post, i|
      if post.image_url == nil
        unused_posts.delete_at(i)
      end
    end

    if unused_posts.length >= POSTS
      POSTS.times do
        @todays_posts.append(unused_posts.shuffle!.pop)
      end
    else
      unused_posts.length.times do
        @todays_posts.append(unused_posts.shuffle!.pop)
      end
    end

    @todays_posts = mark_todays(@todays_posts)
  end

  def get_image(post)
    begin
      tmp_object = LinkThumbnailer.generate(post.url, attributes: [:images], image_limit: 1, image_stats: false)
    rescue LinkThumbnailer::Exceptions => e
      p "#{post.headline} image retrieval error: #{e}"
    else
      post.image_url = tmp_object.images.first.src.to_s
      post.save()
    end
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/sift_helper.rb
module SiftHelper
end

app/helpers/submission_helper.rb
module SubmissionHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Village</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track": "reload" %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Open+Sans:ital,wght@0,300;0,400;0,700;0,800;1,300&family=Playfair+Display:ital,wght@0,400;0,500;0,600;0,700;0,800;0,900;1,400;1,500;1,600;1,700;1,800;1,900&display=swap" rel="stylesheet">
  </head>

  <body>
  <%= turbo_frame_tag "modal" %>
  <div id="menu-bar">

    <div id="site-title">
      <%= link_to about_us_path, data: { "turbo-frame": "modal" } do %>
      <%= image_tag "question.png", :id => 'query-button', :class => 'nav-button'%>
      <% end %>
      <span id="site-header"><i>Village</i></span>

      <%= link_to submissions_new_path, data: { "turbo-frame": "modal" } do %>
      <%= image_tag 'plus.png', :id => 'submission-button', :class => 'nav-button' %>
      <% end %>
    </div>

    <div id="navigation">
      <h4><%= link_to 'noticeboard', "/" %> / <%= link_to 'sift', "/sift" %></h4>
    </div>

    <hr id="top-bar">
    </div>
    <%= yield %>
    <div id="days-running">
      <%= @days_running %>.
    </div>
  </body>
</html>

app/views/shared/_modal.html.erb
<%= turbo_frame_tag "modal" do %>
  <div
    data-controller="modal"
    data-action="keyup@document->modal#handleKeyup"
    class="fixed z-10 inset-0 overflow-y-auto"
    aria-labelledby="modal-title"
    role="dialog"
    aria-modal="true"
  >
    <div class="flex items-end justify-center min-h-screen  pb-20 sm:block sm:p-0 modal-outer">
      <div
        data-action="click->modal#close"
        data-modal-target="wrapper"
        data-transition-enter="ease-out duration-300"
        data-transition-enter-start="opacity-0"
        data-transition-enter-end="opacity-100"
        data-transition-leave="ease-in duration-200"
        data-transition-leave-start="opacity-100"
        data-transition-leave-end="opacity-0"
        class="fixed inset-0 bg-gray-500 bg-opacity-75 transition-opacity"
        aria-hidden="true"
      >
      </div>

      <!-- This element is to trick the browser into centering the modal contents. -->
      <span class="hidden sm:inline-block sm:align-middle sm:h-screen" aria-hidden="true">&#8203;</span>
      <div
        data-modal-target="body"
        data-transition-enter="ease-out duration-300"
        data-transition-enter-start="opacity-0 translate-y-4 sm:translate-y-0 sm:scale-95"
        data-transition-enter-end="opacity-100 translate-y-0 sm:scale-100"
        data-transition-leave="ease-in duration-200"
        data-transition-leave-start="opacity-100 translate-y-0 sm:scale-100"
        data-transition-leave-end="opacity-0 translate-y-4 sm:translate-y-0 sm:scale-95"
        class="inline-block align-bottom bg-white rounded-lg px-4 pt-5 pb-4 text-left overflow-hidden shadow-xl transform transition-all sm:my-8 sm:align-middle sm:max-w-sm sm:w-full sm:p-6"
      >
        <div class="mx-auto flex items-center justify-center h-12 w-12 rounded-full bg-ui-red ">
          <button data-action="modal#close">dismiss</button>
        </div>

        <div class="modal-inner">
          <%= turbo_frame_tag "modal-body" do %>
            <%= yield %>
          <% end %>
        </div>

      </div>
    </div>
  </div>
<% end %>

app/views/sift/index.html.erb
<div class="sift-body">
  <% if @sifts.length != 0 %>
    <% for sift in @sifts %>
  <div class="outer-post sift-post"%>
    <%= image_tag "pin.png", :class => 'post-pin'%>
    <div class="post"%>
    <%= link_to sift.url, target: :_blank, data: { "turbo-frame": "modal" } do %>
    <%= image_tag sift.image_url, :class => "post-image"%>
    <h2> <%= sift.headline %> </h2>
    </div>
    <p><%= link_to "⬆️", "/" %></p>
    <p><%= link_to "⬇️", "/" %></p>
    <% end %>
  </div>

    <% end %>
  <% else %>
    <h1>No new submissions to sift.</h1>
  <% end %>
</div>

app/views/submission/about-us.html.erb
<%= render "shared/modal" do %>
  <br>
  <h1 id="modal-header">What is Village?</h1>
  <br>
  <p><i>Village</i> shows each visitor a set of six stories each day. Every person that comes to the site will see the same stories.</p>
  <br>
  <p>No personalisation.</p>
  <p>No algorithm.</p>
  <br>
  <p>The idea is to create more 'watercooler moments' around high quality content in an age where we are all more remote.</p>
<% end %>

app/views/submission/index.html.erb
<% @todays_posts.each_with_index do |post, i| %>

  <div class="outer-post" id=<%="post-#{@css_random[i]}"%>>
  <%= image_tag "pin.png", :class => 'post-pin'%>
  <div class="post"%>
  <%= link_to post.url, target: :_blank do %>
  <%= image_tag post.image_url, :class => "post-image"%>
  <h2> <%= post.headline %> </h2>
  </div>
  <% end %>
  </div>

  <% if @todays_posts[-1].headline != post.headline %>
    <br>
  <% end %>

<% end %>

app/views/submission/new.html.erb
<%= render "shared/modal" do %>
  <%= simple_form_for @submission, url: submissions_new_path, html: { autocomplete: 'off' } do |f| %>
    <h2><%= f.label :headline %></h2>
    <%= f.input_field :headline, required: true, error: 'Headline is mandatory, please specify one' %>
    <br><br>
    <h2><%= f.label :url %></h2>
    <%= f.input_field :url, label: 'URL', required: true, error: 'A URL is mandatory, please specify one' %>
    <br><br>
    <%= f.button :submit %>
  <% end %>
<% end %>